# Generated by Django 3.2 on 2021-05-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20210506_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
